NeosRulez:
  Backup:
    GoogleCloudStorage:
      backup_identfier: 'backup' # your own backup identifier (extend filename on storage)
      storage_bucket_name: 'my_neos_backups'
      key_file_path: '/var/www/html/Packages/Sites/Acme.Site/Resources/Private/.credentials/credential.json'