#NeosRulez:
#  Backup:
#    GoogleCloudStorage:
#      backup_identfier: 'site-backup' # your own backup identifier (extend filename on storage)
#      storage_bucket_name: 'site_backup_storage'
#      key_file_path: '/data/neos/Data/gcs-ase173b1e093.json'
